services:
  postgres:
    container_name: mi-postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    image: postgres

  biblioteca:
    build: .
    ports:
      - 1000:5000
    depends_on:
      - postgres

volumes:
  postgres-data:
    external: true
    name: postgres-data